#!/usr/bin/env Rscript
# Hongjian Jin @ St Jude Children's Research Hospital
Rver <- as.numeric(paste0(R.version$major, ".", floor(as.numeric(R.version$minor))))


#' Get Script Path
#'
#' Executes GetScriptPath.
#'
#' @param initial.options Argument for GetScriptPath.
#'
#' @return Return value produced by GetScriptPath.
GetScriptPath <- function(initial.options) {
    # return the full path of the current executing script
    # initial.options <- commandArgs(trailingOnly = FALSE)
    file.arg.name <- "--file="
    script.name <- sub(file.arg.name, "", initial.options[grep(file.arg.name, initial.options)])
    script.dirname <- normalizePath(dirname(script.name))
    script.dirname <- paste0(script.dirname, "/")
    return(script.dirname)
}
# ================================================================
#########################
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("stringr"))
suppressPackageStartupMessages(library("patchwork"))
suppressPackageStartupMessages(library("ggpubr"))
suppressPackageStartupMessages(library("limma"))
suppressPackageStartupMessages(library("edgeR"))
suppressPackageStartupMessages(library("reshape2"))
suppressPackageStartupMessages(library("RUVSeq")) # suppressPackageStartupMessages(library("EDASeq"))
suppressMessages(library("ggrepel"))
suppressMessages(library("parallel"))


# ================================================================
library(optparse)
option_list <- list(
    make_option(c("-i", "--rawCount"),
        type = "character", default = NA,
        help = "character. count matrix file generated by AutoMapper"
    ),
    make_option(c("-r", "--report"),
        type = "character", default = NULL,
        help = "character. ${SRM}.report file generated by AutoMapper"
    ),
    make_option(c("-m", "--metaData"),
        type = "character", default = NA,
        help = "character. meta file with at least three required columns:
    \t\t ID,NEWNAME and GROUP,[COLOR,BATCH,GENDER]"
    ),
    make_option(c("-L", "--compList"),
        type = "character", default = NULL,
        help = "character. comparisons.lst
            \t\teach line like Exp_vs_Ctl, where Exp and Ctl must be present in meta$GROUP "
    ),
    make_option(c("-C", "--countCutoff"),
        type = "numeric", default = 0,
        help = "numeric. raw count cutoff. 0 - auto ; usually  a value of >0 and <=10  [default %default]"
    ),
    make_option(c("-c", "--cpmCutoff"),
        type = "numeric", default = 0,
        help = "numeric. CPM cutoff.  0 - auto ; usually a value of >0 and <=5 [default %default]"
    ),
    make_option(c("-o", "--outPrefix"),
        type = "character", default = NA,
        help = "character. outDir/prefix for output files[default %default]"
    ),
    make_option(c("-f", "--filter"),
        type = "logical", default = TRUE,
        help = "logical. whether to filter out non-coding genes [default %default]"
    ),
    make_option(c("-E", "--ERCC"),
        type = "logical", default = TRUE,
        help = "logical. whether to enable ERCC normalization [default %default]"
    ),
    make_option(c("-e", "--ERCC_file"),
        type = "character", default = NULL,
        help = "Add full path to ERCC file"
    ),
    make_option(c("-U", "--unwantedVar"),
        type = "logical", default = FALSE,
        help = "logical. whether to remove unwanted variation using ERCC  [default %default]"
    ),
    make_option(c("-F", "--log2FCcutoff"),
        type = "numeric", default = 1,
        help = "numeric.  log2FC cutoff to define DEGs [default %default]"
    ),
    make_option(c("-P", "--PvalCutoff"),
        type = "numeric", default = 0.05,
        help = "numeric.P.Value cutoff to define DEGs [default %default]"
    ),
    make_option(c("-q", "--qCutoff"),
        type = "numeric", default = 0.05,
        help = "numeric. FDR cutoff to define DEGs [default %default]"
    ),
    make_option(c("-n", "--topn"),
        type = "integer", default = 20,
        help = "integer. define the number of top DEGs (up and down, respectively)"
    )
)

parser <- OptionParser(
    usage = "%prog -i <counts.txt> -m <meta.txt> -o <outPrefix> -E <T|F>
                            [-f <T|F> -C <countCutoff> -c <cpmCutoff> -U <T|F> ]",
    description = "Use ERCCs in bulk RNAseq data to reveal total RNA change or to remove unwanted variation.",
    option_list = option_list,
    epilogue = paste("Examples:\n",
        " i=GSE120015_RSEM_gene_count.txt",
        " m=GSE120015_meta.txt",
        " c=GSE120015_comparison.lst",
        " stdRNAseq.ERCC.Main -r $r -m $m -L $c -o GSE120015_noERCC/$p -E FALSE",
        " stdRNAseq.ERCC.Main.R -i RSEM_count.txt -m sample_meta.txt -L comparison.lst -o DGE_ERCC/${SRM}",
        "\n\n ",
        sep = "\n"
    )
)
args <- NA
result <- tryCatch(
    {
        args <- parse_args(parser, positional_arguments = TRUE) # TRUE = c(0, Inf), FALSE,1,  c(1,2)
    },
    warning = function(w) {
        message(w)
        cat("\n\n")
    },
    error = function(e) {
        message(e)
        cat("\n\n")
    }
)

opt <- args$options
if (any(is.na(args)) || any(is.na(opt))) {
    print_help(parser)
    quit("no")
}

#########################
initial.options <- commandArgs(trailingOnly = FALSE)
######################################################
Rscript_Dir <- GetScriptPath(initial.options)
funcFile1 <- paste0(Rscript_Dir, "stdRNAseq.Func.R")
source(funcFile1)
funcFile2 <- paste0(Rscript_Dir, "stdRNAseq.ERCC.Func.R")
source(funcFile2)

configFile <- paste0(Rscript_Dir, "stdRNAseq.Config.yaml")
if (!file.exists(configFile)) {
    cat("\n Error: configuration file not found:", configFile)
    stop("Exit...")
}
yaml <- ReadYaml(configFile)
pipeline_version <- yaml$PIPELINE


######################################################
reportFile <- opt$report
countFile <- normalizePath(opt$rawCount)
outPrefix <- opt$outPrefix
metaFile <- opt$metaData
filterFlag <- opt$filter
flag_ERCC <- opt$ERCC
cutoff_count <- opt$countCutoff
cutoff_cpm <- opt$cpmCutoff
cutoff_FDR <- opt$qCutoff
cutoff_Pval <- opt$PvalCutoff
cutoff_logFC <- opt$log2FCcutoff
topn <- opt$topn
ercc_control_file <- opt$ERCC_file

if (!file.exists(countFile)) {
    stop(paste0("rawCount file not found:", countFile))
}
if (!file.exists(metaFile)) {
    stop(paste0("rawCount file not found:", metaFile))
}


outDir <- dirname(outPrefix)
if (outDir != ".") {
    dir.create(outDir, showWarnings = FALSE, recursive = TRUE)
}
outDir <- normalizePath(outDir)
prefix0 <- basename(outPrefix)
prefix <- paste0(outDir, "/", prefix0, "_")

######################################################
timeStamp <- gsub(":", ".", strtrim(gsub("[ ]", "_", Sys.time()), 19)) # 8,12
logFile <- paste0(prefix, "log.txt")
# logFile <- paste0(outDir, "/", prefix0, ".log")
msg <- paste0("Run started: ", date())
cat(msg, "\n", file = logFile, append = FALSE)
msg <- paste0("R version: ", paste0(R.version$major, ".", R.version$minor))
cat(msg, "\n")
cat(pipeline_version, "\n")
cat(sprintf("Exclude non-coding genes: %s", filterFlag), "\n")

###############################################
colors4DEGs <- c("#F9ABAB", "#ADADF9", "#F92A2A", "#2727FA", "purple")
names(colors4DEGs) <- c("fill_up", "fill_down", "color_up", "color_down", "GOI")

objMapStat <- list() # keep mapping results

######################################################
msg <- "[Parse AutoMapper ${SRM}.report file]"
cat("\n\n", msg, "\n")
plotFlag <- TRUE
if (!is.null(reportFile)) {
    if (plotFlag) {
        outFile <- paste0(prefix, "MappingReport.tsv")
        msg <- paste0(basename(outFile), "[saved]")
    } else {
        outFile <- NA
        msg <- paste0("Automapper report [processed]")
    }
    mapStat <- ParseMappingReport(reportFile, metaFile, outFile = outFile)
    cat("\n", msg, "\n")
    objMapStat[[length(objMapStat) + 1]] <- mapStat
    names(objMapStat)[length(objMapStat)] <- "mapStat"
} else {
    mapStat <- NA
    msg <- paste0("Warning: AutoMapper Report file is not available!")
    cat("\n\t", msg, "\n")
}
objQC <- list(mapStat = mapStat)

##################################################################

msg <- "[read meta data and count file]"
cat("\n\n", msg, "\n")
cat(sprintf("ERCC mode: %s", flag_ERCC), "\n")

datSet <- ReadMetaAndCountsERCC(metaFile, countFile, filterFlag = FALSE)
counts <- datSet[["counts"]]
counts_ERCC <- datSet[["counts_ERCC"]]
annotation <- datSet[["annotation"]]
meta <- datSet[["meta"]]
if (flag_ERCC == FALSE) {
    msg_1 <- " based on library size normalization."
} else {
    msg_1 <- " based on ERCC normalization."
}
msg <- paste0("used meta data: ", nrow(meta), " x ", ncol(meta))
cat("\n", msg, "\n")
msg <- paste0("used count data: ", nrow(counts), " x ", ncol(counts))
cat("\n", msg, "\n")

msg <- "[check comparisons.lst]"
cat("\n\n", msg, "\n")
if (is.null(opt$compList)) {
    outFile <- paste0(prefix, "comparisons.lst")
    comps <- GetComparisons(meta, outFile = outFile)
    msg <- paste0(basename(outFile), "[saved]")
    cat("\n\t\t", msg, "\n")
} else {
    compListFile <- normalizePath(opt$compList)
    comps <- scan(file = compListFile, character(), quote = "", quiet = T)
}

######################################################

msg <- sprintf("[Standard RNAseq Differential Analysis]  %s", msg_1)
cat("\n\n", msg, "\n")
if (flag_ERCC == TRUE) {
    msg <- "step1. Perform ERCC QC"
    cat("\n\n", msg, "\n")
    # plot ERCC concentration vs log2(count)
    outPrefix1 <- paste0(prefix, "ERCC_QC")
    VizErccConc(counts_ERCC, meta, outPrefix1, ercc_control_file)

    # The most fundamental check is the correlation between the known input concentration of each ERCC transcript and the observed counts in your sequencing data.
    correlations <- ErccQC(counts_ERCC, meta)

    # calculate pct_ERCC and norm.factors
    ErccStat <- CalcERCCnormFactor(counts, counts_ERCC, meta, txtFile = NULL)

    ErccStat$ERCC_COR <- correlations[ErccStat$ID]
    statFile <- paste0(prefix, "ERCC_QC_stat.txt")
    write.table(ErccStat, statFile, sep = "\t", quote = FALSE, row.names = FALSE, col.names = TRUE)
    cat("\n[", basename(statFile), "[saved]")
    cat("\nSave ERCC QC to object.\n")
    Ercc_CV <- as.data.frame(ErccCV(ErccStat))
    # visualize ERCC_metrics
    pdfFile <- paste0(prefix, "ERCC_QC_stat.pdf")
    VizErccStat(ErccStat, outFile = pdfFile)
    shift_test <- lapply(comps, function(x) {
        ErccShiftTest(stat = ErccStat, comp = x, ratio = "pct_ERCC", group = "GROUP")
    })
    shift_test <- as.data.frame(Reduce(rbind, shift_test))
    rownames(shift_test) <- shift_test$comp
    shiftFile <- paste0(prefix, "ERCC_QC_shift.txt")
    write.table(shift_test, shiftFile, sep = "\t", quote = FALSE, row.names = FALSE, col.names = TRUE)
    cat("\n[", basename(shiftFile), "[saved]")
    objQC <- list(mapStat = mapStat, ErccStat = ErccStat, ErccCV = Ercc_CV, ErccShift = shift_test)
}

if (filterFlag) { # if filtering is TRUE, refresh counts, meta and annotation
    datSet <- ReadMetaAndCountsERCC(metaFile, countFile, filterFlag = filterFlag)
    counts <- datSet[["counts"]]
    meta <- datSet[["meta"]]
    annotation <- datSet[["annotation"]]
}
######################################################
if (!any(grepl(".*=\\(.*-.*\\)", comps, ignore.case = T))) {
    invalid_comp_inds <- NULL # 8/26/2021
    for (n in 1:length(comps)) {
        comp <- gsub(" ", "", comps[n])
        keywords <- unlist(strsplit(comp, "_[Vv][Ss]_")) # Exp_vs_Ctl ==> Exp, Ctl
        if (keywords[1] == keywords[2]) {
            invalid_comp_inds <- c(invalid_comp_inds, n)
            msg <- paste0("**Error: Invalid comparison! ", comps[n], " [skipped]**")
            cat("\n\n\t", msg, "\n")
            next
        }
    }
    if (!is.null(invalid_comp_inds)) {
        comps <- comps[-invalid_comp_inds]
    }
}
names(comps) <- paste("C", 1:length(comps), sep = "")
msg <- paste0("Found ", length(comps), " valid comparisons.")
cat("\n\t", msg, "\n")

# ================================================================
msg <- "step.2  perform differetial analyses..\n"
cat("\n\n", msg, "\n")

strLogFC <- "logFC"
strPval <- "P.Value"
strAveExpr <- "AveExpr"

objDE <- ParallelDE2(
    counts = counts, annotation = annotation, meta = meta, comps = comps,
    cutoff_count = cutoff_count, cutoff_cpm = cutoff_cpm, logFile = logFile, ncores = 8, counts_ERCC = counts_ERCC
)
##################################################################
msg <- "Saving rnk files..."
cat("\n\n\t", msg)
d <- dirname(prefix)
p <- basename(prefix)
DEGfiles <- dir(d, pattern = paste0(p, ".*log2CPM.tsv$"), full.names = TRUE)
status <- SaveRnk4GSEA(DEGfiles)
if (status) {
    msg <- "[done]"
} else {
    msg <- "[failed]"
}
cat("\n", msg)

##################################################################
##################################################################

statDEGs <- NULL
statSizes <- NULL
statTopn <- NULL
statComps <- NULL
numDEGs <- list()
topnDEGs <- list()
for (n in 1:length(comps)) {
    objStr <- names(comps)[n]
    diff_table <- objDE[[objStr]]$DE
    meta1 <- objDE[[objStr]]$meta # subset
    sizes <- table(meta$GROUP) # all samples
    comp <- gsub(" ", "", comps[n])
    if (!any(grepl(".*=\\(.*-.*\\)", comps, ignore.case = T))) {
        # keywords <- unlist(strsplit(comp, "_[Vv][Ss]_")) # Exp_vs_Ctl ==> Exp, Ctl
        comp <- gsub("_[vV][Ss]_", "_vs_", comp)
        keywords <- unlist(strsplit(comp, "_vs_")) # Exp_vs_Ctl ==> Exp, Ctl
        sizes1 <- sizes[toupper(keywords)]
        if (any(is.na(sizes1))) { # partial match
            ExpSize <- length(grep(paste0("^", keywords[1], "$"), meta1$GROUP, ignore.case = T))
            CtlSize <- length(grep(paste0("^", keywords[2], "$"), meta1$GROUP, ignore.case = T))
            sizes1 <- c(ExpSize, CtlSize)
            names(sizes1) <- keywords
        }
        strSizes <- paste0(sizes1, collapse = " vs ")
    } else {
        allGroups <- unlist(strsplit(unlist(strsplit(comp, "[=]"))[2], "[-+]"))
        allGroups <- gsub("\\).*", "", gsub(".*\\(", "", allGroups))
        strSizes <- paste(sizes[allGroups], collapse = " , ")
    }

    statSizes <- c(statSizes, strSizes)
    resDEGs <- GetDEGs(diff_table, cutoff_logFC = cutoff_logFC, cutoff_Pval = cutoff_Pval, cutoff_FDR = cutoff_FDR, topn = topn)
    # tmp <-  data.frame(sample_size=strSizes, up=lengths(geneSet)[1],down= lengths(geneSet)[2], total=sum(lengths(geneSet)[1:2]))
    numDEGs[[length(numDEGs) + 1]] <- resDEGs$numDEGs
    topnDEGs[[length(topnDEGs) + 1]] <- resDEGs$topnDEGs
    topNGenes <- paste0(length(resDEGs$topnDEGs$topUpGenes), " up, ", length(resDEGs$topnDEGs$topDownGenes), " down")
    statTopn <- c(statTopn, topNGenes)
}
names(numDEGs) <- names(comps)
names(topnDEGs) <- names(comps)
if (!any(grepl(".*=\\(.*-.*\\)", comps, ignore.case = T))) {
    statDEGs <- data.frame(ID = names(comps), comparison = gsub("_vs_", " vs ", comps), sample_size = statSizes, top_DEGs = statTopn, row.names = NULL)
} else {
    statDEGs <- data.frame(ID = names(comps), comparison = comps, sample_size = statSizes, top_DEGs = statTopn, row.names = NULL)
}

# ================================================================
if (tolower(colnames(counts)[1]) == "gene") {
    dat <- counts[, -1]
} else {
    dat <- counts
}
log2CPM <- cpm(dat, log = T)
# ================================================================

objDEs <- list(QC = objQC, data = datSet, log2CPM = log2CPM, comps = comps, statDEGs = statDEGs, numDEGs = numDEGs, allDE = objDE)
tmpFile <- paste0(prefix, "RNAseqERCC_Results.rds")
#-------merge all results to one and create object----
if (file.exists(tmpFile)) {
    msg <- paste0(basename(tmpFile), "[overwrote existing file]")
} else if (!file.exists(tmpFile)) {
    msg <- paste0(basename(tmpFile), "[saved]")
}
saveRDS(file = tmpFile, objDEs)
cat("\n\t", msg, "\n")

cat("\n\nCheers!\n\n")
garbage <- gc()
q("no")

##################################################################

######################################################
# update log
######################################################
# 8/30/2022, first version
# 8/5/2024,  refactor functions
# 04/11/2025, generate .rnk file for GSEA analysis
# 01/15/2026,  fixed bug: change ^ERCC to ^ERCC-
